"""initial_schema

Revision ID: 26a18716da5f
Revises: 
Create Date: 2026-04-05 03:01:51.740641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26a18716da5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_slug', sa.Text(), nullable=False),
    sa.Column('env', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('activation_status', sa.Text(), nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activation_status IN ('none', 'pending', 'active')", name='ck_billing_activation_status'),
    sa.CheckConstraint("env IN ('dev', 'demo', 'prod')", name='ck_billing_env'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_slug', 'env', name='uq_billing_tenant_env')
    )
    op.create_index('idx_billing_tenant_env', 'billing_usage', ['tenant_slug', 'env'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_slug', sa.Text(), nullable=False),
    sa.Column('env', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('caller_name', sa.Text(), nullable=True),
    sa.Column('phone_hash', sa.Text(), nullable=True),
    sa.Column('needs_callback', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('has_recording', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("env IN ('dev', 'demo', 'prod')", name='ck_calls_env'),
    sa.CheckConstraint("status IN ('missed', 'completed', 'needs-callback')", name='ck_calls_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calls_tenant_callback', 'calls', ['tenant_slug', 'env', 'needs_callback'], unique=False)
    op.create_index('idx_calls_tenant_env_start', 'calls', ['tenant_slug', 'env', 'start_time'], unique=False)
    op.create_index('idx_calls_tenant_status', 'calls', ['tenant_slug', 'env', 'status'], unique=False)
    op.create_table('tenant_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_slug', sa.Text(), nullable=False),
    sa.Column('env', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("env IN ('dev', 'demo', 'prod')", name='ck_tenant_config_env'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_slug', 'env', name='uq_tenant_config_slug_env')
    )
    op.create_index('idx_tenant_config_slug_env', 'tenant_config', ['tenant_slug', 'env'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tenant_config_slug_env', table_name='tenant_config')
    op.drop_table('tenant_config')
    op.drop_index('idx_calls_tenant_status', table_name='calls')
    op.drop_index('idx_calls_tenant_env_start', table_name='calls')
    op.drop_index('idx_calls_tenant_callback', table_name='calls')
    op.drop_table('calls')
    op.drop_index('idx_billing_tenant_env', table_name='billing_usage')
    op.drop_table('billing_usage')
    # ### end Alembic commands ###
